# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '类似网易新闻标题' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'MJRefresh'                         , '3.1.12'
  # Pods for 类似网易新闻标题

  target '类似网易新闻标题Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '类似网易新闻标题UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
